// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { fakeBrowser } from 'wxt/testing';
  export { CSVImportDialog } from '../src/components/CSVImportDialog';
  export { DebugPanel } from '../src/components/DebugPanel';
  export { DetectedSettings } from '../src/components/DetectedSettings';
  export { EditPromptDialog } from '../src/components/EditPromptDialog';
  export { EmptyState } from '../src/components/EmptyState';
  export { ErrorBoundary, ErrorBoundary } from '../src/components/ErrorBoundary';
  export { ExportDialog } from '../src/components/ExportDialog';
  export { FilterBar } from '../src/components/FilterBar';
  export { Footer } from '../src/components/Footer';
  export { GenerateDialog } from '../src/components/GenerateDialog';
  export { ManualAddDialog } from '../src/components/ManualAddDialog';
  export { PromptCard } from '../src/components/PromptCard';
  export { QueueControls } from '../src/components/QueueControls';
  export { SearchBar } from '../src/components/SearchBar';
  export { SettingsDialog } from '../src/components/SettingsDialog';
  export { SortablePromptCard } from '../src/components/SortablePromptCard';
  export { StatusBar } from '../src/components/StatusBar';
  export { recognizeApiProvider, verifyApiKey } from '../src/utils/apiKeyUtils';
  export { CSVParser, CSVParser, CSVParseResult } from '../src/utils/csvParser';
  export { logger, log, LogLevel, LogEntry } from '../src/utils/logger';
  export { PromptActions, PromptActions } from '../src/utils/promptActions';
  export { PromptGenerator, PromptGenerator } from '../src/utils/promptGenerator';
  export { QueueProcessor, QueueProcessor, queueProcessor } from '../src/utils/queueProcessor';
  export { storage } from '../src/utils/storage';
  export { cn } from '../src/lib/utils';
}
