// Generated by wxt
export {}
declare global {
  const CSVImportDialog: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/CSVImportDialog').CSVImportDialog
  const CSVParser: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/csvParser').CSVParser
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DebugPanel: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/DebugPanel').DebugPanel
  const DetectedSettings: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/DetectedSettings').DetectedSettings
  const EditPromptDialog: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/EditPromptDialog').EditPromptDialog
  const EmptyState: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/EmptyState').EmptyState
  const ErrorBoundary: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/ErrorBoundary').ErrorBoundary
  const ExportDialog: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/ExportDialog').ExportDialog
  const FilterBar: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/FilterBar').FilterBar
  const Footer: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/Footer').Footer
  const GenerateDialog: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/GenerateDialog').GenerateDialog
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const ManualAddDialog: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/ManualAddDialog').ManualAddDialog
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const PromptActions: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/promptActions').PromptActions
  const PromptCard: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/PromptCard').PromptCard
  const PromptGenerator: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/promptGenerator').PromptGenerator
  const QueueControls: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/QueueControls').QueueControls
  const QueueProcessor: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/queueProcessor').QueueProcessor
  const SearchBar: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/SearchBar').SearchBar
  const SettingsDialog: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/SettingsDialog').SettingsDialog
  const SortablePromptCard: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/SortablePromptCard').SortablePromptCard
  const StatusBar: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/StatusBar').StatusBar
  const browser: typeof import('wxt/browser').browser
  const cn: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/lib/utils').cn
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const log: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/logger').log
  const logger: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/logger').logger
  const queueProcessor: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/queueProcessor').queueProcessor
  const recognizeApiProvider: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/apiKeyUtils').recognizeApiProvider
  const storage: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const verifyApiKey: typeof import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/apiKeyUtils').verifyApiKey
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { ErrorBoundary } from '/Applications/Github/extension-sora-auto-queue-prompts/src/components/ErrorBoundary'
  import('/Applications/Github/extension-sora-auto-queue-prompts/src/components/ErrorBoundary')
  // @ts-ignore
  export type { CSVParser, CSVParseResult } from '/Applications/Github/extension-sora-auto-queue-prompts/src/utils/csvParser'
  import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/csvParser')
  // @ts-ignore
  export type { LogLevel, LogEntry } from '/Applications/Github/extension-sora-auto-queue-prompts/src/utils/logger'
  import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/logger')
  // @ts-ignore
  export type { PromptActions } from '/Applications/Github/extension-sora-auto-queue-prompts/src/utils/promptActions'
  import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/promptActions')
  // @ts-ignore
  export type { PromptGenerator } from '/Applications/Github/extension-sora-auto-queue-prompts/src/utils/promptGenerator'
  import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/promptGenerator')
  // @ts-ignore
  export type { QueueProcessor } from '/Applications/Github/extension-sora-auto-queue-prompts/src/utils/queueProcessor'
  import('/Applications/Github/extension-sora-auto-queue-prompts/src/utils/queueProcessor')
}
